npx hardhat
npm install --save-dev hardhat @openzeppelin/contracts dotenv ethers hardhat-deploy hardhat-etherscan
require("@nomicfoundation/hardhat-toolbox");
require("dotenv").config();

module.exports = {
    solidity: "0.8.19",
    networks: {
        mumbai: {
            url: process.env.POLYGON_MUMBAI_RPC,
            accounts: [process.env.PRIVATE_KEY]
        },
        polygon: {
            url: process.env.POLYGON_MAINNET_RPC,
            accounts: [process.env.PRIVATE_KEY]
        }
    },
    etherscan: {
        apiKey: process.env.POLYGONSCAN_API_KEY
    }
};
POLYGON_MUMBAI_RPC=YOUR_INFURA_ALCHEMY_RPC
POLYGON_MAINNET_RPC=YOUR_INFURA_ALCHEMY_RPC
PRIVATE_KEY=YOUR_WALLET_PRIVATE_KEY
POLYGONSCAN_API_KEY=YOUR_ETHERSCAN_API_KEY
npx hardhat compile
npx hardhat run scripts/deploy.js --network mumbai
npx hardhat run scripts/deploy.js --network polygon
npx create-next-app@latest frontend
cd frontend
npm install ethers web3modal
npm run dev
git add .
git commit -m "Initial setup with contracts and frontend"
git push origin main
